joint_names: ["tray_1_joint", "tray_2_joint", "tray_3_joint"]
action_name: /tray/joint_trajectory_controller/follow_joint_trajectory
service_ns: /tray/driver
default_vel: 0.3

home: [[0,0,0]]
deliverup: [[0.10, 1.53, 1.87]]
deliverdown: [[1.06, 1.53, 1.47]]      
displayup: [[0.15, 1.53, -1.74]]

