joint_names: ["tray_1_joint", "tray_2_joint", "tray_3_joint"]
action_name: /tray/joint_trajectory_controller/follow_joint_trajectory
service_ns: /tray/driver
default_vel: 0.3

home: [[0.0, 0.0, 0.0]]
deliverup: [[0.0, 1.57, 2]]
deliverdown: [[0.48, 1.57, 1.2]]
displayup: [[0.0, 1.57, -1.57]]
#displaydown: [[0.9, 1.57, 0.8]]
#storetray: [[1.35, 1.57, -1.75]]
